### ISSUE TITLE
Doc change:  Add Tomas Fryda as an author for GLM Booklet.

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#15466]
Please add Tomas Fryda's name and your name as editor here:

![image](https://github.com/h2oai/h2o-3/assets/7231712/33ec4152-7e4b-4612-9a10-6e54d1fd1f28)

and here:

![image](https://github.com/h2oai/h2o-3/assets/7231712/a56ec65d-9b5e-47e9-af1e-361e91634c88)

**Comment by mn-mikke** [comment]
https://h2oai.atlassian.net/browse/PUBDEV-9088
