### ISSUE TITLE
calc_like parameter required for AIC score calculation but not documented

### ISSUE THREAD

**Issue by asedaghat** [h2oai/h2o-3#15529]
**H2O version, Operating System and Environment**
(e.g. 3.38.0.1, Mac OS w/ M1 chip, R v4.0.1).  Please let us know if you're running on K8s/Hadoop and if so, what version.

Support Ticket#: 103849

**Actual behavior**
When testing the new "ml" function for Tweedie and Gamma families in the H2O Generalized Linear Estimator, AIC score isn't displayed by default. We have to set the calc_like=True parameter for the AIC score to display. This parameter is currently undocumented. In contrast, when testing for the Negative Binomial family, the AIC score is displayed without setting the calc_like parameter.

**Expected behavior**
The AIC score should be displayed for all distributions without any extra undocumented parameters. Alternatively, if the calc_like parameter is required for certain distributions, it should be clearly documented.

**Steps to reproduce**

1. Install the latest version of H2O as per the instructions provided.
2. Initialize h2o and import a dataset (train.csv in this case).
3. Define the predictors and response.
4. Define a GLM model with the "ml" function, setting the distribution as Tweedie or Gamma.
5. Train the GLM model.
6. Notice that the AIC score isn't displayed unless you set calc_like=True, which is currently undocumented.
Note: A minimal working code sample is provided in the original description.

**Upload logs**
Not available at the moment. This issue can be reproduced without generating any error logs.

**Screenshots**
N/A

**Additional context**
This issue was discovered during testing of the new "ml" function. For the Tweedie and Gamma distributions, the AIC score calculation requires the calc_like=True parameter, which is currently undocumented. This issue needs to be addressed either by documenting the calc_like parameter properly or by displaying the AIC score without needing to set the calc_like parameter.

**Comment by wendycwong** [comment]
Resolving in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-9090
