### ISSUE TITLE
Support for Python 3.10 and 3.11 in H2O Packages

### ISSUE THREAD

**Issue by asedaghat** [h2oai/h2o-3#15535]
The following H2O packages are currently unavailable for Python 3.10 in client's Artifactory:

JIRA ticket: https://h2oai.atlassian.net/browse/PUBDEV-9099

h2o
h2o_pysparkling_3.0
h2o_pysparkling_scoring_3.0

For more context, support ticket#: 105447

**Comment by wendycwong** [comment]
Support ticket: 104613.
