### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cynthiamaia** [h2oai/h2o-3#15587]
Hello, I'm having trouble understanding what these two accuracies are returned from this command! What is the overall accuracy?
Command
accuracy = model.model_performance().accuracy()
Results
Accuracy: [[0.2571320352154721, 0.8263473053892215]]

**Comment by sarniu** [comment]
the command `accuracy = model.model_performance().accuracy()` return a list of 2 accuracies, the first one being accuracy for the postivie class and the second one the acuuracy for the negative class. 
In this case, it means that the model predicted the positive class correctly 25.7% of the time (first accuracy) and the second accuracy is 82.6% ie model predicted the negative class 82.6% of the time.
Kindly correct me if i'm wrong. Hope this helps.

**Comment by wendycwong** [comment]
Thank you Sarniu.
