### ISSUE TITLE
logging mojo/pojo models using h2o integration for Apache MLFlow

### ISSUE THREAD

**Issue by arunaryasomayajula** [h2oai/h2o-3#15611]
@SF we have implemented MLFlow for tracking model metrics etc. Currently there is fn’s available in MLFlow to log binary models for H2O. We would like to have the option to save mojos and pojos using MLFlow h2o integrated logging. Can this be added to MLFlow?
https://support.h2o.ai/a/tickets/103843

**Comment by wendycwong** [comment]
Some docs here:

https://docs.h2o.ai/mlops/py-client/py-client-examples/external-registry/add-external-registry-model-to-mlops

DAI MLFlow docs:
https://docs.h2o.ai/mlops/external-integration/dai-mlflow

**Comment by wendycwong** [comment]
Take a look at this issue to help with this one: https://github.com/h2oai/model-manager/issues/1796

**Comment by mn-mikke** [comment]
it was covered by https://github.com/h2oai/h2o-3/issues/15654
