### ISSUE TITLE
improve documentation of gam_columns

### ISSUE THREAD

**Issue by rdavis120** [h2oai/h2o-3#15624]
Would it be possible to further explain the gam_columns argument:

https://github.com//h2oai/h2o-3/blob/master/h2o-docs/src/product/data-science/thin_plate_gam.rst

In the example, it is not clear what it means when columns are in vector.  Such as does using c("C12", "C13") imply a tensor interaction between C12 and C13, similar to te(C12, C13) in mccv, and just using "C11" implies s(C11)?
```r
gam_col1 <- list("C11", c("C12","C13"), c("C14", "C15", "C16"), "C17", "C18")
```

**Comment by mn-mikke** [comment]
cc @wendycwong

**Comment by wendycwong** [comment]
@rdavis120 :  for thin-plate regression, the splines can be generated with just 1 predictor or with multiple predictors.  When there are multiple predictors specified as c("C14", "C15", "C16"), it does not mean that it is capturing interaction among the predictors.
