### ISSUE TITLE
Fix Typo on Hadoop Introduction page

### ISSUE THREAD

**Issue by mn-mikke** [h2oai/h2o-3#15629]
https://docs.h2o.ai/h2o/latest-stable/h2o-docs/faq/hadoop.html#can-i-configure-hdfs-multiple-times

<img width="747" alt="Screenshot 2023-07-11 at 17 40 07" src="https://github.com/h2oai/h2o-3/assets/3674621/6f3515ae-2331-4acd-9a08-2a5bb3e74f6d">

The name of the file should be `core-site.xml`

**Comment by Ashwani132003** [comment]
Hi, can i make this correction?

**Comment by mn-mikke** [comment]
@Ashwani132003 yes, of course.
