### ISSUE TITLE
What feature creation and feature selection techniques does H2O offer for enhancing machine learning models?

### ISSUE THREAD

**Issue by TapendraBaduwal** [h2oai/h2o-3#15640]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered, if applicable.

**Additional context**
Add any other context or screenshots about the feature request here.  If there's a reference (paper, book, etc) for this feature, please add that here.

**H2O.ai Devs only**
If there is a support ticket associated with this issue, please post the link here.

**Comment by wendycwong** [comment]
@TapendraBaduwal 

To decide what features to use for building GLM models, you can use the modelselection toolbox (https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/model_selection.html) which can decide for you the following:
- if I want to use m features out of the n features (m<n), what are the best m feature I should use to build my GLM model;

In terms of feature creation, we have the GAM toolbox (https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/gam.html) which will create multiple columns of out of your one feature.

If you want to figure out the relevant features to use for all model like GBM, deeplearning, DRF, GLM, ...., you can use Infogram toolbox (https://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.infogram.html).

Last regarding comprehensive feature creation capabilities, our DAI (https://h2o.ai/platform/ai-cloud/make/h2o-driverless-ai/) will be your best bet.

Thanks, Wendy
