### ISSUE TITLE
Feature Interaction Error: Invalid tree index

### ISSUE THREAD

**Issue by maurever** [h2oai/h2o-3#15679]
Error when feature_interaction method is called from python. 

H2OResponseError: Server error java.lang.IllegalArgumentException:
  Error: Invalid tree index: 254. Tree index must be in range [0, 253].
  Request: POST /3/FeatureInteraction
    data: {'model_id': 'GBM_model_python_1691516425703_1', 'max_interaction_depth': '100', 'max_tree_depth': '100', 'max_deepening': '-1'}

**Comment by wendycwong** [comment]
Here is the dataset: 
[SBA_Loans_train_test.zip](https://github.com/h2oai/h2o-3/files/12307377/SBA_Loans_train_test.zip)

**Comment by maurever** [comment]
The PR is merged.
