### ISSUE TITLE
Fix links to JIRA from the R documentation

### ISSUE THREAD

**Issue by tomasfryda** [h2oai/h2o-3#15691]
R checks now fail due to our move from JIRA.
```
Found the following (possibly) invalid URLs:
  URL: https://0xdata.atlassian.net/browse/TN-9
    From: man/h2o.performance.Rd
    Status: 404
    Message: Not Found
```

**Comment by wendycwong** [comment]
@tomasfryda

Can you provide me with more info and possibly the code to replicate?  I thought I fixed this one in Java backend....


Thanks,
Wendy

**Comment by tomasfryda** [comment]
It looks like it has been resolved in the meanwhile. I think I noticed this issue on jenkins but now when I `grep` for atlassian I don't find any mention. I also ran `make -f scripts/jenkins/Makefile.jenkins test-r-cmd-check` to make sure and it looks OK.
