### ISSUE TITLE
Issue between XGBoost's distributed framework (Rabit) and the linux system

### ISSUE THREAD

**Issue by shashankcheema** [h2oai/h2o-3#15710]
**H2O version, Operating System and Environment**
H2O version - 3.30.0.1
OS - Linux 4.18.0-305.82.1.el8_4.x86_64
Java version: Java 11.0.19 (from Red Hat, Inc.)
Java heap totalMemory: 2.00 GB
Java heap maxMemory: 254.00 GB

**Steps to reproduce**
Steps to reproduce the behavior (with working code on a sample dataset, if possible):
import h2o
h2o.connect(ip="xxx”, port=54321, auth=(username, password))

# Import data
dfh_dev = h2o.import_file(‘xxx.csv')
dfh_val = h2o.import_file(‘yyy.csv')
hyper_params = {
    'learn_rate': 0.30, # Increases the number of trees, default is 0.3
    'max_depth': 5, # default is 6
    # Stopping criteria
    "stopping_rounds": 5,
    "stopping_metric": "AUC",
    "score_tree_interval": 5,
    "stopping_tolerance": 0.001,
    "ntrees": 10000
}
# At this step - below error message been generated.
default_model = train_single_model(
    train_data=dfh_dev,
    validation_data=dfh_val,
    x=list_vars,
    y="B24",
    algorithm="xgboost",
    hyperparams = hyper_params,
    modelsave_dir='./model/',
    results_output_dir='./report/',
    perf_filename="PERF_DEFAULT_MODEL.csv",
    model_id="default_model",
    stopping_metric="AUC",
    perf_metrics_list=[ks_badcapture, auc],
    perf_metrics_options=[{"gains_nbins": 20, "top_captures":[5, 10, 20]},{}]
)

**Upload logs**
Socket Poll Error:Interrupted system call, rabit is configured to keep process running
ERRR: XGBoost training iteration failed
ERRR: ml.dmlc.xgboost4j.java.XGBoostError: Socket Poll Error:Interrupted system call
ERRR: at ml.dmlc.xgboost4j.java.XGBoostJNI.checkCall(XGBoostJNI.java:48)
ERRR: at ml.dmlc.xgboost4j.java.Booster.update(Booster.java:241)
ERRR: at ml.dmlc.xgboost4j.java.XGBoostUpdater$UpdateBooster.call(XGBoostUpdater.java:145)
ERRR: at ml.dmlc.xgboost4j.java.XGBoostUpdater$UpdateBooster.call(XGBoostUpdater.java:111)
ERRR: at ml.dmlc.xgboost4j.java.XGBoostUpdater.run(XGBoostUpdater.java:55)
AssertError:Shutdown: check point must return true, rabit is configured to keep process running
Shutdown: check point must return true

**Screenshots**

**Additional context**
The error message indicates that there was a issue during the training iteration of an XGBoost model when using H2O. It seems that the error originates from the XGBoost library itself, and its related to a problem with the communication between XGBoost's distributed processing framework (Rabit) and the system.

**Comment by shashankcheema** [comment]
@valenad1 - Please let me know if any additional information is required. Thanks in advance.
FYI - Its is mostly happening on distributed environment (not on standalone)

**Comment by shashankcheema** [comment]
@valenad1 - Apologies!! Can you please provide an update on the request. It's currently impacting our production systems.

**Comment by wendycwong** [comment]
Customer support ticket exists.

**Comment by valenad1** [comment]
Ticket is resolved with upgrade of H2O-3, target version not provided.
