### ISSUE TITLE
Problem with the results of shap_explain_row_plot() in python

### ISSUE THREAD

**Issue by Morca97** [h2oai/h2o-3#15722]
**H2O version, Operating System and Environment**
(e.g. 3.38.0.1, Mac OS w/ M1 chip, R v4.0.1).  Please let us know if you're running on K8s/Hadoop and if so, what version.

**Actual behavior**
I have a binary classification problem (0 - Negative Class, 1-Positive Class), and I have deployed an XGBoost algorithm through the AutoML API. When I try to plot shap graphs for local explainability  (shap_explain_row_plot(test, row_index) I have a strange behaviour of the calculated shap values. 
According to shape values logic, a positive shap value should indicate the feature impact towards the positive class, while a negative values an impact of the feature in identifying the negative class. 

In the screenshot, we can see that despite the predicted class is positive, all the shapley values have negative value, how it is possible, there is something to set?

In order to identify the 1 as positive class, I have also relevel both train and test dataset is such way:

## Identify "1" as the Positive Class
train[y] = train[y].relevel("1")
test[y] = test[y].relevel("1")

I think that the same behaviour is achieved on the shap_summary_plot(test) result:

**Screenshots**
![image](https://github.com/h2oai/h2o-3/assets/28482595/880eb849-f23f-4e53-b596-78ea477e5672)
![image](https://github.com/h2oai/h2o-3/assets/28482595/5b6a5a3f-afe5-41f1-b36a-dc2de7ac73c2)

**Comment by tomasfryda** [comment]
It's hard to say whether this is a bug or not. It could be an expected behavior if the BiasTerm is very in favor of positive class or if the threshold for positive outcome is low.

I'd first suggest to do some sanity checks first:
- sum up the contributions and apply the link function and check if it approximately equals* to the prediction probability of the positive class: (python pseudocode)
```python
import numpy as np


def logit_to_prob(l):
    return np.exp(l)/(1+ np.exp(l))

contrib = model.predict_contributions(test[1450,:])
shap_prediction = logit_to_prob(contrib.sum())

abs(model.predict(test[1450,:])[0,2] - shap_prediction) < 1e-3
```

- check the thresholds (this [issue](https://github.com/h2oai/h2o-3/issues/15712) might be helpful to do that)

**Comment by Morca97** [comment]
@tomasfryda The contributions correctly match the prediction probability.
For what concern the threshold the one on which the model is trained is around 0.5, therefore it should be a problem.

However, I think that I have not highlights the fact that the dataset is imbalance, with the 0-Negative class having more instances than the 1-Positive class. I have would like that the model predicts the probability of belonging to the positive class (1), not to the negative (0). 

More precisely, by summing the shapley values contribution and apply the inverse link function I retrieve the probability of belonging to class 0, but i would like that the summary plot present feature shapley values with respect to their impact in belonging to the positive class 1.

**Comment by tomasfryda** [comment]
@Morca97 If `abs(model.predict(test[1450,:])[0,2] - shap_prediction) < 1e-3` worked then the shap values summed up to the positive class, if it doesn't match the positive class in your data, you'll need to relevel the target variable. The `model.predict(...)` returns frame with columns [prediction, prob. of neg. class, prob. of pos. class]. I think you'd need to do something like `df[y] = df[y].relevel("negative_class")` to have negative class as negative class (level 0 => negative class, level 1 => positive class).

**Comment by Morca97** [comment]
It does not change, by apply predict it returns the following frame. In which the negative class is the second column:
<img width="678" alt="image" src="https://github.com/h2oai/h2o-3/assets/28482595/13b3949c-101f-42ad-8bf8-caeb902a57fe">

**Comment by Morca97** [comment]
It doesn't change, since the predict return a frame in which the second column is the one related to the negative class: 
<img width="664" alt="image" src="https://github.com/h2oai/h2o-3/assets/28482595/4b5695ec-5dc8-4e2d-a27e-41a34ed9925d">

**Comment by tomasfryda** [comment]
@Morca97 You have to relevel the training data before you train the model.
