### ISSUE TITLE
Update Conda Distributions on https://anaconda.org/h2oai to support Python 3.10

### ISSUE THREAD

**Issue by rxm7706** [h2oai/h2o-3#15782]
**Is your feature request related to a problem? Please describe.**
https://anaconda.org/h2oai/repo only has distributions for Python 3.7 to Python 3.9 
E.g. https://anaconda.org/h2oai/h2o_pysparkling_scoring_3.3/files?version=3.42.0.1_1

**Describe the solution you'd like**
Create distributions for Python 3.10

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered, if applicable.

**Additional context**
Add any other context or screenshots about the feature request here.  If there's a reference (paper, book, etc) for this feature, please add that here.

**H2O.ai Devs only**
If there is a support ticket associated with this issue, please post the link here.

**Comment by mn-mikke** [comment]
Please wait for the release 3.44.0.1 which will go out approximately in two weeks. This is a duplicated issue to #15535.
