### ISSUE TITLE
Improve default threshold doc for binomial classification 

### ISSUE THREAD

**Issue by maurever** [h2oai/h2o-3#15817]
[Improve docs here](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/performance-and-prediction.html#prediction-threshold)

- show how to get the default threshold using model.default_threshold()
- show how threshold affects prediction (threshold, which is optimized by default by max F1 score.)
- add how to get optimal thresholds for all calculated metrics using model.thresholds_and_metric_scores()
- add reset_threshold_metric() examples for [R](https://github.com/h2oai/h2o-3/blob/c6204a67058bb6b3888e30b07540a3860f3fbdc5/h2o-r/tests/testdir_algos/glm/runit_PUBDEV_7353_GLM_reset_threshold.R) & [Python](https://github.com/h2oai/h2o-3/blob/c6204a67058bb6b3888e30b07540a3860f3fbdc5/h2o-py/tests/testdir_jira/pyunit_pubdev_7353_reset_threshold.py)

**Comment by hannah-tillman** [comment]
Closed w/ https://github.com/h2oai/h2o-3/pull/15902
