### ISSUE TITLE
Rule fit rule extraction

### ISSUE THREAD

**Issue by ssefick** [h2oai/h2o-3#15827]
**H2O version, Operating System and Environment**
Red hat Linux 8

**Actual behavior**
Unable to extract rules. Or rules are not presented in desired/expected a < 5 label 1.

**Comment by maurever** [comment]
Hi @ssefick, please provide a reproducible example of what is wrong. Thanks. 

Here are the instructions:

**Steps to reproduce**
Steps to reproduce the behavior (with working code on a sample dataset, if possible):
1. Do this
2. Do that
3. Do something else
4. See error

**Comment by ssefick** [comment]
This has been resolved. Please close at your earliest convenience.
