### ISSUE TITLE
Document that h2o k8s images doesn't apply security settings by default

### ISSUE THREAD

**Issue by mn-mikke** [h2oai/h2o-3#15881]
Please add note to H2O documentation and to dockerhub that official k8s images doesn't apply any security settings and the default user is ROOT. 

if user requires a secured interface with h2o running in the image, it's his/her responsibility to change user and execution command to add security  parameters before running the image.

 Docker images:
 - https://hub.docker.com/r/h2oai/h2o-open-source-k8s
 - https://hub.docker.com/r/h2oai/h2o-open-source-k8s-minimal
 
 Default command used in docker images: 
 `java -Djava.library.path=/opt/h2oai/h2o-3/xgb_lib_dir -XX:+UseContainerSupport -XX:MaxRAMPercentage=50 -jar /opt/h2oai/h2o-3/h2o.jar`

**Comment by hannah-tillman** [comment]
@mn-mikke I've never edited anything on dockerhub before -- I don't believe I have access at the moment.
