### ISSUE TITLE
How does the deeplearning function work when the input indices for x is out of range

### ISSUE THREAD

**Issue by P-peanutsss** [h2oai/h2o-3#15955]
I've been using h2o.deeplearning function in r to train an autoencoder for feature extraction. I have n rows and p columns for my dataset, with n>>p,  and I mistakenly set x to be 1:n instead of 1:p in my code, but the code actually worked. And when I changed it to 1:p, I found out that the features they extracted were actually different.
So I was wondering how does the function work when I have the x input indices out of range?

**Comment by wendycwong** [comment]
Hi:  

Deeplearning is basically a cascade of different activation functions with parameters weights and thresholds.  When you give it a training set and start the training, it is trying to figure out the parameter weights and thresholds.

Using a very simple example, suppose you have one output node with 3 inputs and one output and only one node.  The relationship between the input and output is 

yi=w1x1i+w2x2i+w3x3i+threshold.

The w1, w2, w3 and threshold will be estimated during training.

It is just a function. You give it inputs, it will calculate and spit out the outputs for you using the above equation.  It does not care about the input ranges or whatever.
