### ISSUE TITLE
Doc: “Learn More” links not working on the h2o-3 page on the website.  https://h2o.ai/platform/ai-cloud/make/h2o/

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#15961]
I noticed that none of the “Learn More” links work on the h2o-3 page on the website.  https://h2o.ai/platform/ai-cloud/make/h2o/

**Comment by hannah-tillman** [comment]
The Enterprise Support "learn more" links have been fixed. Thanks to @leahh2o! :)

The Use Case "learn more" links appear to have a bug that is being looked into. We can follow progress here: https://github.com/h2oai/h2o-aem/issues/1477

**Comment by wendycwong** [comment]
Duplicated.
