### ISSUE TITLE
Add example how to define custom metric from a math formula

### ISSUE THREAD

**Issue by maurever** [h2oai/h2o-3#15960]
Improve this documentation page: https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/custom_metric_func.html

Add an example of how to transform math formula to Map/Reduce/Metric code.

**Comment by wendycwong** [comment]
Support ticket: https://support.h2o.ai/a/tickets/107079

It is not clear how the custom metrics are supported. Examples are given without any explanation of what is what. Here are the links that talked about custom metrics:

https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/custom_metric_func.html
h2o-tutorials/tutorials/custom_metric_func/CustomMetricFuncClassification.ipynb at master · h2oai/h2o-tutorials · GitHub
h2o-tutorials/tutorials/custom_metric_func/utils_model_metrics.py at master · h2oai/h2o-tutorials · GitHub
https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/dev/custom_functions.md
https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/custom_distribution_func.html

We need to clarify it.
