### ISSUE TITLE
pictures on autoML webpages not available

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#15966]
Pictures on autoML web pages: https://h2o.ai/blog/2019/a-deep-dive-into-h2os-automl/ are not available.  The URL links are there:

![image](https://github.com/h2oai/h2o-3/assets/7231712/1d5fb3b6-d05a-42ce-8a84-b5284368a6ae)

**Comment by hannah-tillman** [comment]
Updated :)
