### ISSUE TITLE
Clarify documentation for custom_metric definition and usage

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#15997]
Support ticket: https://support.h2o.ai/a/tickets/107079

It is not clear how the custom metrics are supported.  Examples are given without any explanation of what is what.  Here are the links that talked about custom metrics:
 
https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/custom_metric_func.html
h2o-tutorials/tutorials/custom_metric_func/CustomMetricFuncClassification.ipynb at master · h2oai/h2o-tutorials · GitHub
h2o-tutorials/tutorials/custom_metric_func/utils_model_metrics.py at master · h2oai/h2o-tutorials · GitHub
https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/dev/custom_functions.md
https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/custom_distribution_func.html

We need to clarify it.

**Comment by maurever** [comment]
@wendycwong, I created this issue https://github.com/h2oai/h2o-3/issues/15960 few days ago. I think this one is a duplicate of the first one.

**Comment by wendycwong** [comment]
Duplicated in https://github.com/h2oai/h2o-3/issues/15960.
