### ISSUE TITLE
h2o 3.44.0.3 does not support JDK/Java 21

### ISSUE THREAD

**Issue by ispringer** [h2oai/h2o-3#16066]
**Is your feature request related to a problem? Please describe.**
H2O fails to initialize with error "Only Java versions 8-17 are supported, system version is 21.0.2" if JDK 21 is being used

**Describe the solution you'd like**
Support JDK 21

**Describe alternatives you've considered**
This is preventing me from upgrading my project to Java 21. All other libs we use support Java 21.

**Comment by mn-mikke** [comment]
It's on the roadmap. This issue duplicates https://github.com/h2oai/h2o-3/issues/15772
