### ISSUE TITLE
Upgrade com.fasterxml.jackson.core to version 2.15

### ISSUE THREAD

**Issue by seanlewis08** [h2oai/h2o-3#16115]
Discussed in #16044
Hello, I am building an application using h2o but my container scanner has flagged a vulnerability for one of your Java dependencies (com.fasterxml.jackson.core). Could you please bump the version from 2.14.2 to 2.15.0 in the next release? Below you will see the output of the scanner. Thanks!

 Blocking vulnerabilities found: [
    {
        "id": "PRISMA-2023-0067",
        "status": "fixed in 2.15.0",
        "cvss": 7.5,
        "description": "com.fasterxml.jackson.core_jackson-core package versions before 2.15.0 are vulnerable to Denial of Service (DoS). The package does not properly restrict the size or amount of resources that are requested or influenced by an actor, which can be used to consume more resources than intended and leads to Uncontrolled Resource Consumption (\\'Resource Exhaustion\\').",
        "severity": "high",
        "packageName": "com.fasterxml.jackson.core_jackson-core",
        "packageVersion": "2.14.2",
        "riskFactors": [
            "Has fix",
            "High severity",
            "DoS - High"
        ],
        "impactedVersions": [
            "<2.15.0"
        ],
        "publishedDate": "2023-04-24T11:01:32Z",
        "discoveredDate": "2024-03-07T14:15:28Z",
        "fixDate": "2023-04-24T00:00:00Z",
        "layerTime": "1970-01-01T00:00:00Z",
    }
]

**Comment by valenad1** [comment]
The upgrade will require support for Java 19:

https://github.com/h2oai/h2o-3/issues/15748#issuecomment-1723925218

**Comment by valenad1** [comment]
Duplicate #15748

**Comment by valenad1** [comment]
Duplicate
