### ISSUE TITLE
Isolation forest and extended isolation forest not working with mojo and generic model

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#16120]
support ticket: https://support.h2o.ai/a/tickets/107654

Customers want to be able to load h2o-3 models built with earlier versions and be able to load them back to later h2o-3 models.

In particular, they have tried to save models to mojos in v3.34.0.8 and then load the mojo back to v3.40.0.1 using H2OGeneric Model.  The only two algos that do not work well are isolation forest and extended isolation forest.

Please fix.

**Comment by valenad1** [comment]
Hello, I am sorry for the late response.

First of all, support of Extended Isolation Forest Mojo was added in `3.36.1.1` the EIF Mojo version in `3.34.0.8` doesn't exists. I train it on the [prostate](http://h2o-public-test-data.s3.amazonaws.com/smalldata/prostate/prostate.csv) dataset and I am able import/upload mojo and run the prediction on the  [prostate](http://h2o-public-test-data.s3.amazonaws.com/smalldata/prostate/prostate.csv) in versions

* `3.38.0.1`,
* `3.40.0.1`,
* `3.42.0.1`, 
* `3.44.0.1`, 
* `3.46.0.1`.

I did the same with Isolation Forest, except that the IF Mojo for `3.34.0.8` exists. It works for 

* `3.36.0.1`,
* `3.38.0.1`,
* `3.40.0.1`,
* `3.42.0.1`, 
* `3.44.0.1`, 
* `3.46.0.1`.

Mojos:
- [eif_3_36_1_1.zip](https://github.com/h2oai/h2o-3/files/15027878/eif_3_36_1_1.zip)
- [if_3_34_0_8.zip](https://github.com/h2oai/h2o-3/files/15027797/if_3_34_0_8.zip)
