### ISSUE TITLE
Deprecation warnings with Python 3.12 for "distutils" package

### ISSUE THREAD

**Issue by arunaryasomayajula** [h2oai/h2o-3#16130]
**H2O version, Operating System and Environment**
3.44.0.3
(e.g. 3.38.0.1, Mac OS w/ M1 chip, R v4.0.1).  Please let us know if you're running on K8s/Hadoop and if so, what version.

**Actual behavior**
/site-packages/h2o/plot/_matplotlib.py:6: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
 
/site-packages/h2o/plot/_matplotlib.py:8: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

Deprecation of package "distutils" from Python 3.12 and needs a replacement.

**Expected behavior**

**Steps to reproduce**
Steps to reproduce the behavior (with working code on a sample dataset, if possible):
1. Do this
2. Do that
3. Do something else

**Upload logs**
If you can, please upload the H2O logs.  More information on how to do that is available [here](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/logs.html), or you can use the [`h2o.downloadAllLogs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.downloadAllLogs.html) in R or the [`h2o.download_all_logs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/h2o.html#h2o.download_all_logs) function in Python.  

**Screenshots**

**Additional context**

**Comment by wendycwong** [comment]
From Customer:
