### ISSUE TITLE
H2O3 3.44.0.3 security vulnerabilities reported in SNYK 

### ISSUE THREAD

**Issue by arunaryasomayajula** [h2oai/h2o-3#16134]
**H2O version, Operating System and Environment**
3.44.0.3
**Actual behavior**
Latest vulnerabilities reported by snyk:
 
 1) Allocation of Resources Without Limits or Throttling [High Severity][https://security.snyk.io/vuln/SNYK-JAVA-COMNIMBUSDS-6247633] in com.nimbusds:nimbus-jose-jwt@9.24.4 introduced by unknown:/opt/.venv/lib/python3.11/site-packages/h2o/backend/bin/h2o.jar@unknown > com.nimbusds:nimbus-jose-jwt@9.24.4
  This issue was fixed in versions: 9.37.2

2) Infinite loop [High Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-6254296] in org.apache.commons:commons-compress@1.24.0 introduced by unknown:/opt/.venv/lib/python3.11/site-packages/h2o/backend/bin/h2o.jar@unknown > org.apache.commons:commons-compress@1.24.0
  This issue was fixed in versions: 1.26.0

3) Allocation of Resources Without Limits or Throttling [Medium Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-6254297] in org.apache.commons:commons-compress@1.24.0 introduced by unknown:/opt/.venv/lib/python3.11/site-packages/h2o/backend/bin/h2o.jar@unknown > org.apache.commons:commons-compress@1.24.0
This issue was fixed in versions: 1.26.0

**Expected behavior**
SNYK shouldn't scan for these after the fixes applied.

**Steps to reproduce**
Steps to reproduce the behavior (with working code on a sample dataset, if possible):
1. Do this
2. Do that
3. Do something else

**Upload logs**
If you can, please upload the H2O logs.  More information on how to do that is available [here](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/logs.html), or you can use the [`h2o.downloadAllLogs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.downloadAllLogs.html) in R or the [`h2o.download_all_logs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/h2o.html#h2o.download_all_logs) function in Python.  

**Screenshots**

**Additional context**

**Comment by wendycwong** [comment]
support ticket: https://support.h2o.ai/a/tickets/107560

**Comment by valenad1** [comment]
Fixed by GH-16093 and GH-16102
