### ISSUE TITLE
Validate h2o-3 package on R 4.4 and add test image to jenkins

### ISSUE THREAD

**Issue by tomasfryda** [h2oai/h2o-3#16177]
New R version was released, so we should check if the current release is releasable to CRAN and if not fix the issues so that we don't have to fix the package after the release to be able to put it on CRAN.

Change log:
https://stat.ethz.ch/pipermail/r-announce/2024/000701.html

It would be also nice to run at least some tests to find out that the changes don't break some core functionality (and ideally test this version on jenkins).

**Comment by wendycwong** [comment]
This issue is becoming more urgent now as our customer is asking for it.  We should get this test on Jenkins going.

**Comment by wendycwong** [comment]
Once this is done, we can try to submit our package to CRAN.
