### ISSUE TITLE
The h2o.findSynonyms failed if the 'word' parameter is uknown for the word2vec model

### ISSUE THREAD

**Issue by dmresearch15** [h2oai/h2o-3#16192]
Received the following error when attempting to execute print(h2o.findSynonyms(w2v_model, "National", count = 5)):
Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  object 'score' not found
Curious about the absence of the 'score' parameter.

In contrast, when employing print(h2o.findSynonyms(w2v_model, "national", count = 5)), the score is generated as expected.

**Comment by maurever** [comment]
Hi @dmresearch15. Thanks for reporting this issue. 

It looks like there is a bug, that we cannot return results without an error for an unseen word.

We definitely need to fix it.

**Comment by maurever** [comment]
I reproduced the error by this code:

  ```
job_titles <- h2o.importFile("https://s3.amazonaws.com/h2o-public-test-data/smalldata/craigslistJobTitles.csv",  col.names = c("category", "jobtitle"), col.types = c("String", "String"), header = TRUE)

words <- h2o.tokenize(job_titles, " ")
vec <- h2o.word2vec(training_frame = words)

// pass    
syn <- h2o.findSynonyms(vec, "teacher", count = 20)
print(syn)

// fail    
syn2 <- h2o.findSynonyms(vec, "Tteacher", count = 20)
print(syn2)
```

**Comment by dmresearch15** [comment]
I'm presently incorporating this into my project. It's helpful to have a timeframe for resolving this issue.
