### ISSUE TITLE
Real-Time Data Analysis with Predictive Analytics

### ISSUE THREAD

**Issue by dmresearch15** [h2oai/h2o-3#16309]
I am particularly interested in predictive analytics using streaming data, with applications in areas such as real-time fraud detection, financial risk management, predictive maintenance for Industry 4.0, and so on. Like to build robust and scalable system for real-time predictive analytics by integrating H2O with Apache Flink, Kafka and Beam but limited to.

**Comment by valenad1** [comment]
Hello @dmresearch15,

what is the question we can answer?
