### ISSUE TITLE
constrained GLM issues: 1. constrained not satisfied, 2. duplicate/conflicting contrains error thrown

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#16312]
Support ticket: https://support.h2o.ai/a/tickets/108488

Issue 1. Constraints are not strictly satisfied;
Issue 2. NPE when specifying beta constraints
Issue 3. Constraints that are not conflicting or duplicated but are detected to be such by the code.

**Comment by wendycwong** [comment]
issues 2/3 are resolved due to bugs in implementation.
issue 1 is due to algorithm arriving at line search failure or arriving at a state where no further progress can be made.  When this happens before the constraints are satisfied, we are stuck with solution that do not satisfy all constraints.

**Comment by valenad1** [comment]
@wendycwong moved milestone to next Major. It was merged to master
