### ISSUE TITLE
HGLM model errors out and also gives MSE=0 for models

### ISSUE THREAD

**Issue by arunaryasomayajula** [h2oai/h2o-3#16316]
**H2O version, Operating System and Environment**
3.46.0.1, https://support.h2o.ai/a/tickets/108551

**Actual behavior**
Hierarchical GLM model training code:
 
# Select Splitting ratio
ratio = 0.80
z=[len(hdf.columns)-1]
total_rows = hdf.shape[0]
train_size = int(total_rows*ratio)
# Split data into test and train
splits = hdf.split_frame(ratios=[0.8], seed=1)
hdftrain = splits[0]
hdftest = splits[1]
 
# hdftrain = hdf[0:train_size]
# hdftest = hdf[train_size:]
# dftrain
h2o_glm = H2OGeneralizedLinearEstimator(HGLM=True,
                                        family= "gaussian", rand_family=["gaussian"],
                                        random_columns=z,
                                         rand_link=["identity"], calc_like=True,
                                          #lambda_ = 0,
                                          #compute_p_values = True,
                                          #generate_scoring_history = True
                                         )
h2o_glm.train(x_vars, response_col, training_frame= hdftrain)
print(h2o_glm)

**Expected behavior**
The HGLM model shouldn't error out before training.

**Steps to reproduce**
Steps to reproduce the behavior (with working code on a sample dataset, if possible):
1. Do this
2. Do that
3. Do something else

**Upload logs**
If you can, please upload the H2O logs.  More information on how to do that is available [here](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/logs.html), or you can use the [`h2o.downloadAllLogs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.downloadAllLogs.html) in R or the [`h2o.download_all_logs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/h2o.html#h2o.download_all_logs) function in Python.  

**Screenshots**

**Additional context**

**Comment by wendycwong** [comment]
This issue will be resolved in this issue: https://github.com/h2oai/h2o-3/issues/8487.  I am closing this for now.
