### ISSUE TITLE
[docs] Group by clarifications

### ISSUE THREAD

**Issue by hutch3232** [h2oai/h2o-3#16338]
I was trying to reference these docs: https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-munging/groupby.html

I think a few clarifications could be helpful. Some ideas:

1. Could an example of using the `col.names` `gb.control` arg be provided? I could not figure out how to do it. Saw this issue so perhaps it's not working? https://github.com/h2oai/h2o-3/issues/12731
2. Under the "R only" header it shows `nrow` being an argument and the description refers to defining column names. That seems like a mistake.
3. Perhaps `na.methods` should be presented as a bullet underneath `gb.control` for clarity.
4. This note:

> If a list smaller than the number of columns groups is supplied, then the list will be padded by ignore.

Could that be clarified? Is it saying the `gb.control` options are recycled? Could an example be provided where options are by-variable?

**Comment by wendycwong** [comment]
@hutch3232 

An example code here:

![image](https://github.com/user-attachments/assets/052599fc-cf0b-401e-88ec-b4af2ea3fa2b)

So, sorry. Will fix.  May take a while.

**Comment by hannah-tillman** [comment]
closed with: https://github.com/h2oai/h2o-3/pull/16404
