### ISSUE TITLE
3.46.0.3 vulnerabilities 

### ISSUE THREAD

**Issue by arunaryasomayajula** [h2oai/h2o-3#16332]
**H2O version, Operating System and Environment**
3.46.0.3

**Actual behavior**
Tested 56 dependencies for known issues, found 1 issue, 1 vulnerable path.

Issues with no direct upgrade or patch:

✗ External Control of File Name or Path [Critical Severity][https://security.snyk.io/vuln/SNYK-PYTHON-H2O-6125908] in h2o@3.46.0.3

introduced by h2o@3.46.0.3

No upgrade or patch available

Organization: model-development-puas

Package manager: pip

Target file: requirements.txt

**Expected behavior**
SNYK should not give any CVE warnings after scan.

**Steps to reproduce**
Steps to reproduce the behavior (with working code on a sample dataset, if possible):
1. Do this
2. Do that
3. Do something else

**Upload logs**
If you can, please upload the H2O logs.  More information on how to do that is available [here](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/logs.html), or you can use the [`h2o.downloadAllLogs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/reference/h2o.downloadAllLogs.html) in R or the [`h2o.download_all_logs()`](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/h2o.html#h2o.download_all_logs) function in Python.  

**Screenshots**

**Additional context**

**Comment by mohamedasni** [comment]
Fixed in #16357 cc @valenad1

**Comment by valenad1** [comment]
Duplication
