### ISSUE TITLE
Add to H2O-3 docs or github docs that we do not support numpy2 for now.

### ISSUE THREAD

**Issue by wendycwong** [h2oai/h2o-3#16412]
Users using installing numpy2 will not work with h2o-3.  The work around is

![image](https://github.com/user-attachments/assets/983fbf46-f4a5-4a44-9d82-048bcf388d91)

We need to alert the users about this before we fix it here: https://github.com/h2oai/h2o-3/issues/16295

**Comment by hannah-tillman** [comment]
Closed w/: https://github.com/h2oai/h2o-3/pull/16434
