### ISSUE TITLE
Feature Request: Ability to extract underlying XGBoost booster object from h2oxgboostestimator

### ISSUE THREAD

**Issue by stephenpardy** [h2oai/h2o-3#6823]
Currently when using the `H2OXGBoostEstimator` model class there does not seem to be anyway to access the underlying booster object. For my particular use case this is required. 

I have seen [this question](https://stackoverflow.com/questions/52528611/extract-native-xgboost-model-from-h2oxgboostestimator-model-in-python) on Stackoverflow which asks if this is possible. The answer given there is to use `convert_H2OXGBoostParams_2_XGBoostParams` to refit the model in native XGBoost. Unfortunately this is not possible for my use case. 

Alternatively, if the exact model cannot be made available, it would be helpful to have access to the `trees_to_dataframe` method of XGBoost or something equivalent. 

Thank you for the excellent package and all of the work.

**Comment by valenad1** [comment]
Hello @stephenpardy,

Thank you for the question. If you convert your model to MOJO, there is boosterBytes in the zip of your trained model. You can upload it to native xgboost and use as you wish.

Is it enough for your usecase?

**Comment by stephenpardy** [comment]
Thank you @valenad1 - it sounds like it might meet my use case. Let me test today and tomorrow and report back.

**Comment by stephenpardy** [comment]
Yes this will work. Thank you.
